server.port=8080

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true

logging.level.org.springframework.web=DEBUG
logging.level.org.xhy.function_calling=DEBUG

spring.web.resources.static-locations=classpath:/static/

server.servlet.session.timeout=30m

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


siliconflow.api.url=https://api.siliconflow.cn/v1/chat/completions
siliconflow.api.token=123

qwen.api.token=123